name: "custom-app-base-plugin"
description: "Languages application base plugin"
types: 
  - app
tags:
  - application
  - kotlin
  - container
inputs:
  - label: "Project name:"
    type: text
    name: "project_name"
    global: true
  - label: "Project group id:"
    type: text
    name: "project_group_id"
    global: true
    condition:
      variable: "language"
      operator: "=="
      value: "kotlin"
  - label: "Project version:"
    type: text
    name: "project_version"
    default: "0.0.1-SNAPSHOT"
computedInputs:
  "app_class_name": "{{project_name|title|replace(' ', '')}}"